SELECT info.ITEM_ID, info.ITEM_NAME, info.RARITY
FROM ITEM_INFO info
JOIN ITEM_TREE child
ON info.ITEM_ID = child.ITEM_ID
JOIN ITEM_INFO parent
ON child.PARENT_ITEM_ID = parent.ITEM_ID
WHERE parent.RARITY = "RARE"
ORDER BY info.ITEM_ID DESC;