SELECT info.ID, name.FISH_NAME, info.LENGTH
FROM FISH_INFO info
JOIN FISH_NAME_INFO name
ON info.FISH_TYPE = name.FISH_TYPE
WHERE (info.FISH_TYPE, info.LENGTH) in (
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    WHERE LENGTH IS NOT NULL
    GROUP BY FISH_TYPE
)
ORDER BY info.ID ASC;